--
-- PostgreSQL database dump
--

-- Dumped from database version 14.3 (Debian 14.3-1.pgdg110+1)
-- Dumped by pg_dump version 14.3 (Debian 14.3-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Staff; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Staff" (
    "Id" integer NOT NULL,
    "FirstName" text,
    "SecondName" text,
    "Patronymic" text,
    "Age" integer NOT NULL,
    "JobPosition" text,
    "PhoneNumber" character varying(11),
    "Email" character varying(50)
);


ALTER TABLE public."Staff" OWNER TO postgres;

--
-- Name: Staff_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Staff" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Staff_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Staff; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Staff" ("Id", "FirstName", "SecondName", "Patronymic", "Age", "JobPosition", "PhoneNumber", "Email") FROM stdin;
1	John	Smith	Michael	28	Software Developer	15551234567	john.smith@example.com
2	Emily	Johnson	Rose	28	Project Manager	15552345678	emily.johnson@example.com
3	Michael	Williams	James	35	Software Developer	15553456789	michael.williams@example.com
4	Sarah	Brown	Anne	26	UX Designer	15554567890	sarah.brown@example.com
5	David	Jones	Robert	42	System Architect	15555678901	david.jones@example.com
6	Jennifer	Garcia	Marie	31	DevOps Engineer	15556789012	jennifer.garcia@example.com
7	Christopher	Miller	Thomas	35	Frontend Developer	15557890123	christopher.miller@example.com
8	Jessica	Davis	Lynn	27	QA Engineer	15558901234	jessica.davis@example.com
9	Matthew	Rodriguez	Joseph	28	Team Lead	15559012345	matthew.rodriguez@example.com
10	Amanda	Wilson	Grace	33	Software Developer	15550123456	amanda.wilson@example.com
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260124221828_Init	9.0.0
\.


--
-- Name: Staff_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Staff_Id_seq"', 10, true);


--
-- Name: Staff PK_Staff; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Staff"
    ADD CONSTRAINT "PK_Staff" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- PostgreSQL database dump complete
--

